name = "SMLMVis"
uuid = "7f8ec1f1-d3bf-4329-ba46-362bfda99182"
authors = ["klidke@unm.edu"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
